cors:
  originPatterns: http://localhost:3000,http://localhost:8787,https://erudio.com.br
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest_with_springboot?useTimezone=true&serverTimezone=UTC
    username: root
    password: 789789

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8787

springdoc:
  paths-to-match: /api/**/v1/**
  swagger-ui:
    use-root-path: true

