CREATE TABLE PERSON(
    ID         bigint(20) NOT NULL AUTO_INCREMENT,
    FIRST_NAME VARCHAR(80),
    LAST_NAME  VARCHAR(80),
    ADDRESS    VARCHAR(255),
    GENDER     VARCHAR(10),
    PRIMARY KEY (id)
);